#!/bin/bash

if [[ -z "$SWAYSOCK" ]]; then
	echo "SWAYSOCK not set" > /dev/stderr
	exit 1
fi

IMAGE_NAME=set-wallpaper:custom

PROCESSED_WALLPAPERS_DIR=$HOME/.local/processed-wallpapers
mkdir -p $PROCESSED_WALLPAPERS_DIR
IMAGE_HOME=/home/user

CONFIG_FILE_PATH="$HOME/.config/wallpaper-directories"
if ! [[ -f "$CONFIG_FILE_PATH" ]]; then
    echo "~/wallpapers" > "$CONFIG_FILE_PATH"
fi

if [[ $1 != --no-build ]]; then
	docker build -t $IMAGE_NAME --build-arg ALPINE_VERSION=3.21 .
else
	shift
fi

INTERACTION=-d
# INTERACTION="-it --entrypoint /bin/sh"
# INTERACTION=-it
# --privileged

# -u $(id -u):$(id -g) \

docker run \
    $INTERACTION \
    --rm \
    --privileged \
    -u $(id -u):$(id -g) \
    -e SWAYSOCK=/tmp/sway.sock \
    -v $SWAYSOCK:/tmp/sway.sock \
    -v ${HOME}/wallpapers:${IMAGE_HOME}/wallpapers \
    -v ${PROCESSED_WALLPAPERS_DIR}:${IMAGE_HOME}/.local/processed-wallpapers \
    -v ${CONFIG_FILE_PATH}:${IMAGE_HOME}/.config/wallpaper-directories \
    $IMAGE_NAME "$@"

    # --entrypoint /bin/sh \
    #     -c 'ls -al /tmp'
